src/StormPort.h
This PR changes `StormPort.h` to check for `_WIN32` and `_WIN64` instead of `WIN32` and `WIN64` to get better compiler coverage on Windows.
At present, MSYS2 gcc under Windows will assume the platform is Linux when you include `StormLib.h`. This is because `WIN32` and `WIN64` are user-defined macros that aren't defined by all compilers. For example, Visual Studio passes `/DWIN32` to the compiler by default.
The difference is that `_WIN32` is automatically defined by every mainstream C(++) **compiler** on Windows for both 32-bit and 64-bit builds, which means that checking for `_WIN32` is sufficient to detect the platform. You can then check `_WIN64` to narrow down a 64-bit target. [This page details the macros defined by mainstream …
=> Better Windows platform detection

.gitignore, StormLib.xcodeproj/project.pbxproj
There were a lot of the crypto files missing from being built and linked in via Xcode, causing the resulting framework/library via xcodebuild to be useless. I also added the OS X intermediaries to the gitignore.
=> Fixed building the framework/library on OS X

Premake5.lua, stormlib_dll/DllMain.c
modify result type. mingw compile error.
add Premake5.lua for generate project file or makefile.
how to use premake5. visit [wiki](https://github.com/premake/premake-core/wiki)
=> modify result type. mingw compile error. add Premake5.lua

CMakeLists.txt
If the value of O_LARGEFILE is unspecified, it will be defined as 1 (O_WRONLY) causing permission errors on readonly data regardless of the intended open flags passed in.
=> Define O_LARGEFILE as 0 on FreeBSD.

CMakeLists.txt
If you run CMake and then build on *nix without having bzip2-devel installed, build will fail with linker error for -lbz2. This is due to the fact that ZLIB_BZIP2_FILES is added to compile target for WIN32 only. So, bzip2 is compiled from source on Windows but not for *nix. This change fails the CMake build if bzip2 is missing.
=> Require bzip2 on *nix

src/FileStream.cpp, src/StormLib.h
correct type for GetLastError and SetLastError is DWORD (would cause warnings because of unsigned/signed conversion if using a DWORD variable to store the result)
=> use DWORD for get/setlasterror

src/SFileReadFile.cpp
The standard behaviour for fseek / SetFilePointer when the new pointed value would be negative is to not move the pointer and return an error.
See : https://msdn.microsoft.com/en-us/library/windows/desktop/aa365541(v=vs.85).aspx `If a new file pointer is a negative value, the function fails, the file pointer is not moved, and the code returned by GetLastError is ERROR_NEGATIVE_SEEK.`
=> SFileSetFilePointer error when new pointer is <0

CMakeLists.txt, src/StormLib.h
Since #90 seemed to be too much changes at once, I'll try to clean up the CMakelists.txt bit by bit to provide new features and easier update/selection of dependencies.
For now, I just bumped the cmake required version to 2.8.12 since the CMakelists.txt already uses target_* commands, and added a new defined `STORMLIB_NO_AUTO_LINK`.
This lets the user chose how to link the library by defining `STORMLIB_NO_AUTO_LINK` before inclusion.
In terms of feature, it is exactly the same as `__STORMLIB_SELF__`, but I added a new define in case `__STORMLIB_SELF__` needs to be used for anything else in the future.
I also added `STORMLIB_NO_AUTO_LINK` to the cmake `INTERFACE` property so that someone can link directly against it using CMake.
Note that I did note make it `PUBLIC` so that it is not …
=> Stormlib no auto link

CMakeLists.txt
The options UNICODE and BUILD_DYNAMIC_MODULE were only changing the name
of the libraries and not the flags used for compilation.
I removed them for now, but if we want to add Unicode/Runtime version to
CMake it will be possible later.
This fixes #114 as the .lib created by CMake on windows can no more be
mistaken for another one. If people need to build a specific version of
the library, they can for now use the cmake cache to change the /M(D/T)
flag and/or add the UNICODE and _UNICODE defines.
I changed the option name for the test executable so that it won't
conflict with other projects, and made sure BUILD_TESTING is checked.
When BUILD_TESTING (the official option for CTest) is ON,
STORM_BUILD_TESTS is by default ON. If BUILD_TESTING is set to OFF, then
STORM_BUILD_TESTS can only be …
=> CMake: Remove misleading opts add DLL support - fixes #114

CMakeLists.txt
Compile it really only if STORM_BUILD_TESTS is enabled and link it against
compiled StormLib library instead of compiling all source files again.
=> Fix compiling storm_test executable

src/SFileReadFile.cpp, src/StormPort.h
This addresses an apparent oversight in the following commit:
- 951f416398b3aa0b32969b4a391a3103443ad99e
An error is not actually set, even though the return value now correctly
indicates failure.  Per the documentation for [`SetFilerPointer ()`][1],
this should be set to `ERROR_NEGATIVE_SEEK` on Windows.  On Mac/Linux,
this would be `EINVAL` as per the documentation for [`fseek ()`][2].
[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365541(v=vs.85).aspx
[2]: http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html
=> Set SFileSetFilePointer error when new pointer < 0

src/SFileReadFile.cpp
This addresses a bug introduced in:
- fe652fe4a6e02041194a0f1b29a0086bd99fb14d
Brackets were not properly included, causing `SFILE_INVALID_POS` to be
returned whenever `DeltaPos` was less than zero, instead of only when
the resulting position was negative.
I apologize for not noticing this earlier.
=> Add brackets in SFileSetFilePointer when pointer < 0

CMakeLists.txt
Make sure to use the system headers when using system zlib (linux).
=> Cmake: System zlib and bz2 headers on linux

src/SFileVerify.cpp
This might not be a common thing, but having multiple file types appended onto a file is perfectly fine with Warcraft3 and the World editor(although saving the map loses all of that). A test case would be getting any .exe, appending an .w3m to it and then appending some other file type like .zip(I used the cat command for that). When the map is opened it works just fine, but trying to get its signature info from StormLib fails.
=> Support for mpq not being the last part of a file

src/StormPort.h
This makes StormLib usable with C++ stdlib (e.g. the <algorithm> header which defines std::min/max)
=> StormPort: Suppress `min/max` macros from windows

src/StormPort.h
looks better if we want to differ INVALID_PARAMETER and incorrect seek I think?
maybe this is wrong
=> change ERROR_NEGATIVE_SEEK to ESPIPE

StormLib_vs19.vcxproj
Noticed this inconsistency in the solution configuration for ReleaseUD for Win32, where the character set was not set.
=> Ensure ReleaseUD for Win32 uses Unicode

src/SFileGetFileInfo.cpp
MP3 files are a bit messy because of the many possible headers, but they were used for Warcraft 3 music before 1.32; Warcraft 3 maps are useful to add because of custom campaigns.
=> Add more file extensions

src/FileStream.cpp
If the file fails to open, the file handle must be invalidated.
/cc @AJenbo
=> FileStream: Ensure file handle invalidation on error

src/SBaseCommon.cpp
Mac-specific functions aren't all that useful, simply replaces them with a platform-agnostic implementation. Fixes #212
=> Fix big endian on non-Mac

src/StormPort.h
Do not assume mmap by default for the fallback platform, unless it's in a list of platforms that we know have mmap
Refs #215
=> StormPort.h: Do not assume mmap support

src/FileStream.cpp
Before this fix, `Get/SetLastError` on non-Windows behaved incorrectly when used from multiple threads.
=> Make nLastError thread-local

CMakeLists.txt
Similar to my https://github.com/ladislav-zezula/CascLib/pull/204/commits/4cae0facbbb7ff1238c5e0b4a1a713ab54189b45
LibTomCrypt also should be allowed to be external, but I don't have a use for it yet, so wouldn't be able to verify
=> Allow using external zlib and bzip libs on windows

src/StormLib.h
I ran into a regression linking v9.23 with a golang library. This PR reverts the definitions of `TFileStream` and `SFileAddFileEx` to those used in v9.22 to fix the compilation errors.
=> Fix C compliance for StormLib.h

CMakeLists.txt
This will change the .lib/.dll output file name to `StormLib` instead `storm` when build with cmake for Windows.
BTW, using `RUNTIME_OUTPUT_NAME` instead of `OUTPUT_NAME` will only change the .dll file name (leave the .lib file name untouched).  I could change the PR if that is more appropriate.
=> Change output name of Windows cmake to StormLib

src/pklib/implode.c
otherwise it wont work properly on platforms where short has a different (not 16) size
=> use USHRT_MAX in FindRep

CMakeLists.txt
Reopen of https://github.com/ladislav-zezula/StormLib/pull/263 with updated `master`.
From previous PR:
Hello,
I'm in the process of writing Rust bindings for [namigator](https://github.com/namreeb/namigator) and I want to statically link as much as possible in order to guarantee reproducibility and require as few external dependencies as possible.
Adding this option means that I won't have to manually include and set up zlib and bzip2.
Let me know if you want any changes or want it done another way.
Sorry about the PR spam. :/
=> Add `STORM_USE_BUNDLED_LIBRARIES` option that defaults to OFF

src/pklib/pklib.h
The enums document the dependences between sizes of different structures.
=> Add enums for sizes of different data structures in `pklib.h`.

src/SBaseFileTable.cpp
Since `BSWAP_TMPQHEADER` will modify the header data, the MD5 check would always fail on big endian platforms.
=> MPQ_V4: Byteswap header after md5 is verified

src/SFileListFile.cpp, src/StormLib.h
Adds capability to add in-memory list file entries to MPQs.
For map editing tools it's convenient to not have to write new list file entries to disk prior to updating listfiles in MPQs.
=> Add to listfile from memory

src/adpcm/adpcm.h
`ChannelCount` and `nCmpType` were the wrong way round.
=> Fix CompressADPCM argument order

CMakeLists.txt
Users will now be able to do:
```cmake
find_package(StormLib CONFIG REQUIRED)
target_link_libraries(SomeTarget PRIVATE StormLib::storm)
```
Note that vcpkg now relies on this CMakeLists.txt, so if this is merged and a new version is released it will make it even easier to consume the library as it automatically detects config files.
=> Install CMake config file to allow `find_package(StormLib)`

CMakeLists.txt
Presently when using cmake+vcpkg there doesn't seem to be a way to compile stormlib as unicode, this change adds the STORM_UNICODE option (which mirrors [CASC_UNICODE](https://github.com/ladislav-zezula/CascLib/blob/master/CMakeLists.txt#L78), making it possible to use a portfile to compile a unicode version of stormlib on windows.
This passed local testing (for opening/reading MPQ files using UTF16 filepaths) using a portfile.cmake with the following contents...
<details>
<summary>portfile.cmake</summary>
> 
> message("using vcpkg overlay port for stormlib")
> 
> vcpkg_from_github(
>     OUT_SOURCE_PATH SOURCE_PATH
>     REPO TheNitesWhoSay/StormLib
>     REF d65f31f21a3b5b4e2e3b5c17a68253126fdcaeee
>     SHA512 7288fc229299e1b3e171c30b4f125eca327c0f8b65695ac6aab1b039c15595d64c10c9786da74 …
=> Add STORM_UNICODE option for windows cmake builds

src/pklib/implode.c
Use int instead of short to fix a (false positive) vulnerability warning.
Even though is not necessary (because the value is limited to 0x204), the generated code seems to be better as well, because a zero-extension becomes unnecessary.
=> use int instead of short in FindRep

src/SBaseCommon.cpp
Always free SectorOffsets in case of failure in AllocateSectorOffsets and reset the pointer in TMPQFile.
Thou, you might want to do it the other way and leave if there since there is not much point to read after a failure and FreeFileHandle does that anyway.
=> free/release SectorOffsets of TMPQFile in AllocateSectorOffsets

src/SBaseFileTable.cpp
- dwHashTableSize must be a power of two, otherwise HASH_INDEX_MASK does not work
=> validate dwHashTableSize

src/StormPort.h
Makes it easier to add StormLib as a dependency
=> Win: Only define NOMINMAX if it's not already defined
